// TODO Implement this library.
// This file is automatically generated by `flutter test` when running
// `flutter pub run build_runner build --watch`
// See: https://pub.dev/packages/build_runner/usage

import 'package:dio/dio.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

@GenerateMocks([Dio])
class MockDio extends Mock implements Dio {}
