// import 'dart:ui';
import 'dart:ui_web';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA70001,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.cyan800,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.gray400,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: appTheme.blueA400,
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.blueGray100,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: FontsConstant.Poppins,
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: Color(0XFF000000),
          fontSize: 14.fSize,
          fontFamily: FontsConstant.Poppins,
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.black900,
          fontSize: 12.fSize,
          fontFamily: FontsConstant.Poppins,
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black900,
          fontSize: 24.fSize,
          fontFamily: FontsConstant.Inter,
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 13.fSize,
          fontFamily: FontsConstant.Inter,
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 20.fSize,
          fontFamily: FontsConstant.Poppins,
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: FontsConstant.Montserrat,
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.black900,
          fontSize: 14.fSize,
          fontFamily: FontsConstant.Poppins,
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFF4F4F4),
    primaryContainer: Color(0XAB606060),
    secondaryContainer: Color(0XFF200E32),

    // Error colors
    errorContainer: Color(0XFFFF860B),
    onError: Color(0X97FFE5CB),
    onErrorContainer: Color(0XA2212121),

    // On colors(text colors)
    onPrimary: Color(0XFF162E38),
    onPrimaryContainer: Color(0XFF0C0C0C),
    onSecondaryContainer: Color(0XA200A4FD),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue300 => Color(0XFF63ACD4);
  Color get blueA400 => Color(0XFF3472FF);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray200 => Color(0XFFB8C3D4);
  Color get blueGray20001 => Color(0XFFB9C5D5);
  Color get blueGray900 => Color(0XFF162E38);

  // Cyan
  Color get cyan5090 => Color(0X90CCFDFF);
  Color get cyan800 => Color(0XFF1D858A);
  Color get cyan900 => Color(0XFF003366);
  Color get cyan200Cc => Color(0XCC8EDBDA);

  // DeepOrange
  Color get deepOrange10090 => Color(0X90FFD8BB);
  Color get deepOrange200 => Color(0XFFFFBB89);
  Color get deepOrange20090 => Color(0X90FFBA89);
  Color get deepOrange300 => Color(0XFFFF7968);

  // Gray
  Color get gray100 => Color(0XFFF6F7F8);
  Color get gray10001 => Color(0XFFF7F7F7);
  Color get gray10002 => Color(0XFFF5F5F5);
  Color get gray400 => Color(0XFFB8B8B8);
  Color get gray40001 => Color(0XFFBCBCBC);
  Color get gray500 => Color(0XFFAAAAAA);
  Color get gray50001 => Color(0XFFA5A5A5);
  Color get gray5059 => Color(0X59F9F9F9);
  Color get gray600 => Color(0XFF808080);
  Color get gray60001 => Color(0XFF71757A);
  Color get gray900 => Color(0XFF1C1B1F);
  Color get gray900A2 => Color(0XA2212121);

  // Grayf
  Color get gray5003f => Color(0X3F9A9A9A);

  // LightGreen
  Color get lightGreen200 => Color(0XFFD6E4AA);

  // Orange
  Color get orange200 => Color(0XFFFFBE7E);
  Color get orange600 => Color(0XFFFF860B);
  Color get orange700 => Color(0XFFFF8000);

  // Red
  Color get red300 => Color(0XFFCD7A91);

  // Teal
  Color get tealA40090 => Color(0X9038FF93);

  // White
  Color get whiteA700 => Color(0XFFFEFEFE);
  Color get whiteA70001 => Color(0XFFFFFFFF);

  // Yellow
  Color get yellow10097 => Color(0X97FFE5CB);
  Color get yellow400 => Color(0XFFFBE468);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
