name: ucleankim
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>2.12.0 <=4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  lottie: 1.2.1
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  flutter_svg_provider: ^1.0.7
  grouped_list: ^5.1.2
  url_launcher: ^6.2.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  mockito: ^5.4.4
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/lottieFiles/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanSemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500